Made pypi upload simpler

diff --git a/.github/workflows/cleanup_pypi.yml b/.github/workflows/cleanup_pypi.yml
--- a/.github/workflows/cleanup_pypi.yml
+++ b/.github/workflows/cleanup_pypi.yml
@@ -1,16 +1,32 @@
 name: Cleanup PyPI
 on:
   workflow_call:
+    inputs:
+      environment:
+        description: CI environment to run in (test.pypi or production.pypi)
+        type: string
+        required: true
   workflow_dispatch:
     inputs:
       dry-run:
         description: List packages that would be deleted but don't delete them
         type: boolean
         default: false
+      environment:
+        description: CI environment to run in
+        type: choice
+        required: true
+        default: test.pypi
+        options:
+          - test.pypi
+          - production.pypi
+
 jobs:
   cleanup_pypi:
     name: Remove Nightlies from PyPI
     runs-on: ubuntu-latest
+    environment:
+      name: ${{ inputs.environment }}
     env:
       PYPI_CLEANUP_PASSWORD: ${{secrets.PYPI_CLEANUP_PASSWORD}}
       PYPI_CLEANUP_OTP: ${{secrets.PYPI_CLEANUP_OTP}}
@@ -18,6 +34,19 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
+      - if: ${{ vars.PYPI_HOST == '' }}
+        run: |
+          echo "Error: PYPI_HOST is not set in CI environment '${{ inputs.environment }}'"
+          exit 1
+      - if: ${{ vars.PYPI_CLEANUP_USERNAME == '' }}
+        run: |
+          echo "Error: PYPI_CLEANUP_USERNAME is not set in CI environment '${{ inputs.environment }}'"
+          exit 1
+      - if: ${{ vars.PYPI_MAX_NIGHTLIES == '' }}
+        run: |
+          echo "Error: PYPI_MAX_NIGHTLIES is not set in CI environment '${{ inputs.environment }}'"
+          exit 1
 
       - name: Install Astral UV
         uses: astral-sh/setup-uv@v6
@@ -27,8 +56,8 @@ jobs:
       - name: Run Cleanup
         run: |
           set -x
-          uv -v sync --only-group pypi --no-install-project
-          uv -v run --no-sync -s scripts/pypi_cleanup.py ${{ inputs.dry-run && '--dry' || '' }} \
+          uv sync --only-group pypi --no-install-project
+          uv run --no-sync -s scripts/pypi_cleanup.py ${{ inputs.dry-run && '--dry' || '' }} \
             --index-hostname "${{ vars.PYPI_HOST }}" \
             --username "${{ vars.PYPI_CLEANUP_USERNAME }}" \
             --max-nightlies ${{ vars.PYPI_MAX_NIGHTLIES }}
